version: "3.1"

services:
  mongo:
    container_name: bun-backebd-test-db
    image: mongo:7.0.2
    restart: always
    volumes:
      - db_data:/data/db
    ports:
      - "28018:27017"

volumes:
  db_data:
